language: java
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11

script:
  - ./gradlew clean sonarqube -Dsonar.login=$SONAR_KEY

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email: false
